# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kadu Diógenes
email: kadu@fnix.com.br
description: >- # this means to ignore newlines until "baseurl:"
  A programmer daily. Write about software is the most incredible thing of the universe, right? No, it just helps me
  organize my ideas and keep working, probably you will note this from my writings. I'm also doing this to gain emapthy
  and exchange experiences, so get in touch!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kadu_diogenes
github_username:  kdiogenes

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
talkyard_server_url: https://comments-for-kdiogenes-github-io.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
